services:
  app:
    image: golang:1.26-alpine
    command: ["go", "run", "/lab/main.go"]
    volumes:
      - ./main.go:/lab/main.go:ro

  prometheus:
    image: prom/prometheus:v3.7.3
    attach: false
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
      - ./rules_test.yml:/etc/prometheus/rules_test.yml:ro

  alertmanager:
    image: prom/alertmanager:v0.31.0
    attach: false
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
