services:
  app:
    image: golang:1.26-alpine
    command: ["go", "run", "/lab/main.go"]
    volumes:
      - ./main.go:/lab/main.go:ro

  prometheus:
    image: prom/prometheus:v3.7.3
    attach: false
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro

  grafana:
    image: grafana/grafana:13.2.3
    attach: false
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml:ro

  # alertmanager:
  #   image: prom/alertmanager:v0.31.0
  #   attach: false
  #   volumes:
  #     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
