// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID           int64
	Key          string
	Payload      []byte
	CreatedAt    pgtype.Timestamptz
	PublishedAt  pgtype.Timestamptz
	TraceContext []byte
}
