// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO
  outbox (
    partition_key,
    event_type,
    payload,
    trace_context
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4
  ) RETURNING id, partition_key, event_type, payload, created_at, published_at, trace_context
`

type CreateOutboxEventParams struct {
	PartitionKey string
	EventType    string
	Payload      []byte
	TraceContext []byte
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.PartitionKey,
		arg.EventType,
		arg.Payload,
		arg.TraceContext,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.PartitionKey,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.TraceContext,
	)
	return i, err
}

const getOutboxEvents = `-- name: GetOutboxEvents :many
SELECT
  id, partition_key, event_type, payload, created_at, published_at, trace_context
FROM
  outbox
WHERE
  published_at IS NULL
ORDER BY
  id
LIMIT
  $1 FOR
UPDATE
  SKIP LOCKED
`

func (q *Queries) GetOutboxEvents(ctx context.Context, limit int32) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.PartitionKey,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.TraceContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
