#!/usr/bin/env bash
# Shared plumbing. Every script here performs some part of the same
# migration, so the pieces live here once.

set -euo pipefail
cd "$(dirname "$0")"

readonly MONO=postgres://postgres:postgres@localhost:5555/db
readonly PAY=postgres://postgres:postgres@localhost:5556/db
readonly SVC=http://localhost:8088
readonly BIN=./zero-downtime-split

# -qtAX: no headers, no alignment, no psqlrc. Every caller parses the output.
m()   { psql "$MONO" -qtAX -v ON_ERROR_STOP=1 -c "$1"; }
p()   { psql "$PAY"  -qtAX -v ON_ERROR_STOP=1 -c "$1"; }
ctl() { curl -fsS -XPOST "$SVC/control?$1" >/dev/null; }
stat_of() { curl -fsS "$SVC/stats" | sed -E "s/.*\"$1\":([^,}]*).*/\1/"; }

ms() { date +%s%3N; }
rule() { printf '\n── %s ───────────────────────────────\n' "$*"; }

require_seed() {
  m 'SELECT 1 FROM lab.payments LIMIT 1' >/dev/null 2>&1 && return 0
  echo "no lab.payments: psql $MONO -f seed.sql (the stack must be up)" >&2
  exit 1
}

# The service runs for the length of one script and is torn down with it.
# Its routing always starts where the migration starts: everything on the
# monolith.
start_service() {
  # Built, not "go run". go run leaves a compiled child that is not $!, so
  # killing $! leaves a server holding :8088 -- and the next run's health
  # check then passes against the *previous* run's process.
  go build -o "$BIN" .
  "$BIN" serve >out/serve.log 2>&1 &
  SERVICE_PID=$!
  for _ in $(seq 50); do
    curl -fsS "$SVC/stats" >/dev/null 2>&1 && break
    sleep 0.1
  done
  ctl 'writes=monolith&reads=monolith&reset=1'
}

# Must not end on a failing command: bash propagates an EXIT trap's status,
# so a kill of an already-dead process makes the whole script exit 1.
stop_service() {
  if [[ -n ${SERVICE_PID:-} ]]; then
    kill "$SERVICE_PID" 2>/dev/null || true
  fi
  wait 2>/dev/null || true
}

# Tear the replication down to nothing. Subscriptions own a slot on the
# publisher, so the order matters: drop the subscriber side first, or the
# slot is left behind holding WAL on the monolith forever.
teardown_replication() {
  p  "DROP SUBSCRIPTION IF EXISTS payments_sub" >/dev/null 2>&1 || true
  m  "DROP SUBSCRIPTION IF EXISTS rollback_sub" >/dev/null 2>&1 || true
  m  "DROP PUBLICATION  IF EXISTS payments_pub" >/dev/null 2>&1 || true
  p  "DROP PUBLICATION  IF EXISTS rollback_pub" >/dev/null 2>&1 || true
  m  "SELECT pg_drop_replication_slot(slot_name) FROM pg_replication_slots" >/dev/null 2>&1 || true
  p  "SELECT pg_drop_replication_slot(slot_name) FROM pg_replication_slots" >/dev/null 2>&1 || true
}

# Start from the same place every time. These scripts move data and
# sequences between two databases, and a run that starts on the wreckage of
# the previous one measures the previous one.
#
# It is worth knowing why that wreckage exists: after a cutover with reverse
# replication in place, rows arrive in the monolith carrying ids generated by
# the new database, and an arriving row does not advance the sequence that
# would have produced it. The monolith's sequence is left behind its own
# table, and its next local insert collides -- the same failure as §2, in the
# other direction, waiting for whoever rolls back.
reset_monolith() {
  psql "$MONO" -q -v ON_ERROR_STOP=1 -f seed.sql >/dev/null
}

# The tables, and nothing else. This is what you get if you read the manual,
# create what the subscription needs, and stop there -- which is what
# everyone does, because nothing tells you the list is longer than that.
#
# Three things the monolith has are missing, and section 3 of backfill.sh
# puts a number on each: the (order_id) index, the foreign key, and the two
# sequence positions.
create_new_schema() {
  p "
    DROP SCHEMA IF EXISTS lab CASCADE;
    CREATE SCHEMA lab;
    CREATE TABLE lab.orders (
      id         bigserial   PRIMARY KEY,
      created_at timestamptz NOT NULL DEFAULT now()
    );
    CREATE TABLE lab.payments (
      id         bigserial   PRIMARY KEY,
      order_id   bigint      NOT NULL,
      created_at timestamptz NOT NULL DEFAULT now()
    );
  " >/dev/null
}

# The rest of the schema, which has to wait until the rows are there: the
# foreign key validates every existing row when it is added, so adding it
# before the COPY validates nothing and adding it during the COPY races it.
finish_new_schema() {
  p "CREATE INDEX ON lab.payments (order_id)" >/dev/null
  p "ALTER TABLE lab.payments
       ADD CONSTRAINT payments_order_id_fkey
       FOREIGN KEY (order_id) REFERENCES lab.orders (id)" >/dev/null
}

# The read path's own query. Not a synthetic benchmark -- it is exactly what
# GET /pay runs, which is why a missing index here shows up as service
# latency rather than as a number in a report nobody reads.
readonly READ_Q="SELECT count(*) FROM lab.payments WHERE order_id = 100000"

# Execution time and the access method the planner chose, from one EXPLAIN.
scan() {
  local db=$1 plan
  plan=$($db "EXPLAIN (ANALYZE, BUFFERS OFF) $READ_Q")
  printf '%9s ms   %s\n' \
    "$(sed -n 's/.*Execution Time: \([0-9.]*\) ms.*/\1/p' <<<"$plan")" \
    "$(grep -om1 'Seq Scan\|Index Scan\|Index Only Scan\|Bitmap Heap Scan' <<<"$plan")"
}

# How far behind the subscriber is, in bytes of WAL the publisher has
# produced and the subscriber has not confirmed. This is the number the
# monolith cares about: unconfirmed WAL is disk it may not reclaim.
lag_bytes() {
  m "SELECT coalesce(pg_wal_lsn_diff(pg_current_wal_lsn(), confirmed_flush_lsn), 0)::bigint
     FROM pg_replication_slots WHERE slot_name = 'payments_sub'"
}

# How far behind in time. Postgres computes this itself on the publisher, so
# unlike comparing two hand-taken samples it carries no skew from the gap
# between the two queries.
lag_time() {
  m "SELECT coalesce(replay_lag, '0'::interval)::text
     FROM pg_stat_replication WHERE application_name = 'payments_sub'"
}

# Rows the subscriber has not applied yet. The subscriber is counted FIRST on
# purpose: whatever is written in the gap between the two counts then lands
# on the publisher's side of the subtraction, so the answer is an
# over-estimate rather than a negative number.
rows_behind() {
  local a b
  a=$(rows_pay); b=$(rows_mono)
  echo $((b - a))
}

# srsubstate: i initialising, d copying, f copy finished, s synchronised,
# r ready (streaming). Each table syncs independently, with its own worker
# and its own state, so the subscription is only following the publisher
# once every one of them says 'r'. This returns how many do not yet.
tables_syncing() { p "SELECT count(*) FROM pg_subscription_rel WHERE srsubstate <> 'r'"; }

rows_mono() { m 'SELECT (SELECT count(*) FROM lab.orders) + (SELECT count(*) FROM lab.payments)'; }
rows_pay()  { p 'SELECT (SELECT count(*) FROM lab.orders) + (SELECT count(*) FROM lab.payments)'; }

# The cutover itself. Five statements, and their order is the whole
# difference between a held request and an outage. The timings come back in
# globals so the caller can print them.
do_cutover() {
  local t

  # Never freeze into a backlog. The freeze lasts as long as whatever the
  # subscriber still has to apply, so freezing while it is behind makes the
  # outage the size of the queue. Wait until it is nearly caught up with
  # writes still flowing -- that costs nobody anything -- and only then
  # freeze and drain the small remainder.
  #
  # The threshold is not zero because rows_behind cannot resolve below its
  # own sampling skew, which is ~25 rows at this write rate.
  while (( $(rows_behind) > 100 )); do :; done

  t0=$(ms)

  ctl 'freeze=on'
  quiesce=$(( $(ms) - t0 ))

  t=$(ms)
  while (( $(rows_pay) < $(rows_mono) )); do :; done
  drain=$(( $(ms) - t ))
  outstanding=$(lag_bytes)

  t=$(ms)
  p "DROP SUBSCRIPTION payments_sub" >/dev/null; dropsub=$(( $(ms) - t ))

  t=$(ms)
  p "SELECT setval('lab.orders_id_seq',   (SELECT max(id) + 1000 FROM lab.orders));
     SELECT setval('lab.payments_id_seq', (SELECT max(id) + 1000 FROM lab.payments))" >/dev/null
  seqfix=$(( $(ms) - t ))

  # Rollback is a subscription pointing the other way, and it has to be
  # created now rather than when it is needed: copy_data = false means it
  # carries everything written from this moment on, and nothing before it.
  t=$(ms)
  p "CREATE PUBLICATION rollback_pub FOR TABLE lab.orders, lab.payments" >/dev/null
  m "CREATE SUBSCRIPTION rollback_sub
     CONNECTION 'host=payments port=5432 user=postgres password=postgres dbname=db'
     PUBLICATION rollback_pub WITH (copy_data = false)" >/dev/null
  reverse=$(( $(ms) - t ))

  t=$(ms)
  ctl 'writes=payments&reads=payments'
  flip=$(( $(ms) - t ))

  ctl 'freeze=off'
  total=$(( $(ms) - t0 ))
}
