// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/alerts.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Alerts_GetAlert_FullMethodName = "/alerts.Alerts/GetAlert"
)

// AlertsClient is the client API for Alerts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertsClient interface {
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertResponse, error)
}

type alertsClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertsClient(cc grpc.ClientConnInterface) AlertsClient {
	return &alertsClient{cc}
}

func (c *alertsClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertResponse)
	err := c.cc.Invoke(ctx, Alerts_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertsServer is the server API for Alerts service.
// All implementations must embed UnimplementedAlertsServer
// for forward compatibility.
type AlertsServer interface {
	GetAlert(context.Context, *GetAlertRequest) (*GetAlertResponse, error)
	mustEmbedUnimplementedAlertsServer()
}

// UnimplementedAlertsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertsServer struct{}

func (UnimplementedAlertsServer) GetAlert(context.Context, *GetAlertRequest) (*GetAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedAlertsServer) mustEmbedUnimplementedAlertsServer() {}
func (UnimplementedAlertsServer) testEmbeddedByValue()                {}

// UnsafeAlertsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertsServer will
// result in compilation errors.
type UnsafeAlertsServer interface {
	mustEmbedUnimplementedAlertsServer()
}

func RegisterAlertsServer(s grpc.ServiceRegistrar, srv AlertsServer) {
	// If the following call panics, it indicates UnimplementedAlertsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Alerts_ServiceDesc, srv)
}

func _Alerts_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertsServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Alerts_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertsServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Alerts_ServiceDesc is the grpc.ServiceDesc for Alerts service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Alerts_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alerts.Alerts",
	HandlerType: (*AlertsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlert",
			Handler:    _Alerts_GetAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/alerts.proto",
}
