// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/alerts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_proto_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_proto_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *GetAlertRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertResponse) Reset() {
	*x = GetAlertResponse{}
	mi := &file_proto_alerts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertResponse) ProtoMessage() {}

func (x *GetAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alerts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertResponse.ProtoReflect.Descriptor instead.
func (*GetAlertResponse) Descriptor() ([]byte, []int) {
	return file_proto_alerts_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *GetAlertResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_alerts_proto protoreflect.FileDescriptor

const file_proto_alerts_proto_rawDesc = "" +
	"\n" +
	"\x12proto/alerts.proto\x12\x06alerts\"\x17\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fGetAlertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x10GetAlertResponse\x12#\n" +
	"\x05alert\x18\x01 \x01(\v2\r.alerts.AlertR\x05alert\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok2G\n" +
	"\x06Alerts\x12=\n" +
	"\bGetAlert\x12\x17.alerts.GetAlertRequest\x1a\x18.alerts.GetAlertResponseB\x0eZ\falerts/protob\x06proto3"

var (
	file_proto_alerts_proto_rawDescOnce sync.Once
	file_proto_alerts_proto_rawDescData []byte
)

func file_proto_alerts_proto_rawDescGZIP() []byte {
	file_proto_alerts_proto_rawDescOnce.Do(func() {
		file_proto_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alerts_proto_rawDesc), len(file_proto_alerts_proto_rawDesc)))
	})
	return file_proto_alerts_proto_rawDescData
}

var file_proto_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_alerts_proto_goTypes = []any{
	(*Alert)(nil),            // 0: alerts.Alert
	(*GetAlertRequest)(nil),  // 1: alerts.GetAlertRequest
	(*GetAlertResponse)(nil), // 2: alerts.GetAlertResponse
}
var file_proto_alerts_proto_depIdxs = []int32{
	0, // 0: alerts.GetAlertResponse.alert:type_name -> alerts.Alert
	1, // 1: alerts.Alerts.GetAlert:input_type -> alerts.GetAlertRequest
	2, // 2: alerts.Alerts.GetAlert:output_type -> alerts.GetAlertResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_alerts_proto_init() }
func file_proto_alerts_proto_init() {
	if File_proto_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alerts_proto_rawDesc), len(file_proto_alerts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alerts_proto_goTypes,
		DependencyIndexes: file_proto_alerts_proto_depIdxs,
		MessageInfos:      file_proto_alerts_proto_msgTypes,
	}.Build()
	File_proto_alerts_proto = out.File
	file_proto_alerts_proto_goTypes = nil
	file_proto_alerts_proto_depIdxs = nil
}
