package main

import (
	"context"
	"encoding/json"
	"errors"
	"kafka/db"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/twmb/franz-go/pkg/kadm"
	"github.com/twmb/franz-go/pkg/kerr"
	"github.com/twmb/franz-go/pkg/kgo"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

const (
	brokers           = "localhost:29092"
	databaseURL       = "postgresql://postgres:postgres@localhost:5555/db?sslmode=disable"
	outboxBatchSize   = 100
	outboxInterval    = time.Second
	group             = "alerts"
	topic             = "alerts"
	partitions        = 3
	replicationFactor = -1
	eventTypeHeader   = "event_type"
)

type alert struct {
	SensorID string  `json:"sensor_id"`
	Value    float64 `json:"value"`
}

func main() {
	ctx := context.Background()

	otel.SetTracerProvider(sdktrace.NewTracerProvider())
	otel.SetTextMapPropagator(propagation.TraceContext{})

	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		panic("new pool: " + err.Error())
	}
	if err := pool.Ping(ctx); err != nil {
		panic("pool ping: " + err.Error())
	}
	defer pool.Close()

	pool.Exec(ctx, `
	BEGIN;

CREATE TABLE outbox (
  id bigint generated by default as identity PRIMARY KEY,
  partition_key text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  trace_context jsonb
);

CREATE INDEX idx_outbox_unpublished ON outbox (id)
WHERE
  published_at IS NULL;

COMMIT;
`)

	client, err := kgo.NewClient(kgo.SeedBrokers(brokers))
	if err != nil {
		panic("new kafka client: " + err.Error())
	}
	defer client.Close()

	admin := kadm.NewClient(client)

	if _, err := admin.CreateTopic(ctx, partitions, replicationFactor, nil, topic); err != nil &&
		!errors.Is(err, kerr.TopicAlreadyExists) {
		panic("create topic: " + err.Error())
	}

	producer, err := kgo.NewClient(kgo.SeedBrokers(brokers))
	if err != nil {
		panic("new kafka producer: " + err.Error())
	}
	defer producer.Close()

	payload, err := json.Marshal(alert{
		SensorID: "deviceID+measurement",
		Value:    10.2,
	})
	if err != nil {
		panic("marshal: " + err.Error())
	}

	r := relay{pool: pool, producer: producer}
	go r.run(ctx)

	consumer, err := kgo.NewClient(
		kgo.SeedBrokers(brokers),
		kgo.ConsumerGroup(group),
		kgo.ConsumeTopics(topic),
		// Committing is done by hand, after the handler has succeeded. On the
		// automatic setting an offset can be committed for a record whose
		// handler then fails, which loses the event.
		kgo.DisableAutoCommit(),
		// A group joining a topic it has never read starts at the beginning, so
		// a consumer added later still sees the history.
		kgo.ConsumeResetOffset(kgo.NewOffset().AtStart()),
	)
	if err != nil {
		panic("new kafka client: " + err.Error())
	}
	defer consumer.Close()

	go runConsumer(ctx, consumer)

	queries := db.New(pool)
	if _, err := queries.CreateOutboxEvent(ctx, db.CreateOutboxEventParams{
		PartitionKey: "sensorID",
		EventType:    "sensor.reading.recorded",
		Payload:      payload,
	}); err != nil {
		panic("create outbox event: " + err.Error())
	}

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)
	<-stop

	slog.InfoContext(ctx, "shuting down")
}
