package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"kafka/db"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/twmb/franz-go/pkg/kadm"
	"github.com/twmb/franz-go/pkg/kerr"
	"github.com/twmb/franz-go/pkg/kgo"
)

const (
	brokers           = "localhost:29092"
	databaseURL       = "postgresql://postgres:postgres@localhost:5555/db?sslmode=disable"
	outboxBatchSize   = 100
	outboxInterval    = time.Second
	topic             = "alerts"
	partitions        = 3
	replicationFactor = -1
	eventTypeHeader   = "event_type"
)

type alert struct {
	SensorID string  `json:"sensor_id"`
	Value    float64 `json:"value"`
}

func main() {
	ctx := context.Background()

	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		panic("new pool: " + err.Error())
	}
	if err := pool.Ping(ctx); err != nil {
		panic("pool ping: " + err.Error())
	}
	defer pool.Close()

	pool.Exec(ctx, `
	BEGIN;

CREATE TABLE outbox (
  id bigint generated by default as identity PRIMARY KEY,
  partition_key text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  trace_context jsonb
);

CREATE INDEX idx_outbox_unpublished ON outbox (id)
WHERE
  published_at IS NULL;

COMMIT;
	
	`)

	client, err := kgo.NewClient(kgo.SeedBrokers(brokers))
	if err != nil {
		panic("new kafka client: " + err.Error())
	}
	defer client.Close()

	admin := kadm.NewClient(client)

	if _, err := admin.CreateTopic(ctx, partitions, replicationFactor, nil, topic); err != nil &&
		!errors.Is(err, kerr.TopicAlreadyExists) {
		panic("create topic: " + err.Error())
	}

	producer, err := kgo.NewClient(kgo.SeedBrokers(brokers))
	if err != nil {
		panic("new kafka client: " + err.Error())
	}
	defer producer.Close()

	payload, err := json.Marshal(alert{
		SensorID: "deviceID+measurement",
		Value:    10.2,
	})
	if err != nil {
		panic("marshal: " + err.Error())
	}

	r := relay{pool: pool, producer: producer}
	go r.run(ctx)

	queries := db.New(pool)
	if _, err := queries.CreateOutboxEvent(ctx, db.CreateOutboxEventParams{
		PartitionKey: "sensorID",
		EventType:    "sensor.reading.recorded",
		Payload:      payload,
	}); err != nil {
		panic("create outbox event: " + err.Error())
	}

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)
	<-stop

	slog.InfoContext(ctx, "shuting down")
}

type relay struct {
	pool     *pgxpool.Pool
	producer *kgo.Client
}

func (r *relay) run(ctx context.Context) {
	ticker := time.NewTicker(outboxInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			slog.InfoContext(ctx, "outbox relay stopped")
			return
		case <-ticker.C:
			// A burst should not have to wait one tick per batch to drain.
			for {
				published, err := r.publishBatch(ctx)
				if err != nil {
					slog.ErrorContext(ctx, "publish outbox batch", "err", err)
					break
				}
				if published < int(outboxBatchSize) {
					break
				}
			}
		}
	}
}

func (r *relay) publishBatch(ctx context.Context) (int, error) {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return 0, fmt.Errorf("begin transaction: %w", err)
	}
	defer func() {
		if err := tx.Rollback(ctx); err != nil && !errors.Is(err, pgx.ErrTxClosed) {
			slog.WarnContext(ctx, "rollback transaction", "err", err)
		}
	}()

	queries := db.New(tx)
	events, err := queries.GetOutboxEvents(ctx, outboxBatchSize)
	if err != nil {
		return 0, fmt.Errorf("get outbox events: %w", err)
	}
	if len(events) == 0 {
		return 0, nil
	}

	ids := make([]int64, len(events))
	for _, e := range events {
		// Get trace from outbox

		headers := []kgo.RecordHeader{
			{Key: eventTypeHeader, Value: []byte(e.EventType)},
		}
		// Add observability headers

		if err := r.producer.ProduceSync(ctx, &kgo.Record{
			Key:     []byte(e.PartitionKey),
			Topic:   topic,
			Value:   e.Payload,
			Headers: headers,
		}).FirstErr(); err != nil {
			return 0, fmt.Errorf("publish event %d: %w", e.ID, err)
		}

		ids = append(ids, e.ID)
	}

	if _, err := tx.Exec(ctx, "UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])", ids); err != nil {
		return 0, fmt.Errorf("mark published: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return 0, fmt.Errorf("commit: %w", err)
	}

	slog.InfoContext(ctx, "published outbox events", "count", len(ids))

	return len(ids), nil
}
