version: "3"

tasks:
  run: go run .

  squawk: squawk 'migrations/*.sql'

  sqlc:
    - sqlc generate -f sqlc.yaml
    - sqlc vet -f sqlc.yaml

  proto: protoc
    --go_out=.
    --go_opt=paths=source_relative
    --go-grpc_out=.
    --go-grpc_opt=paths=source_relative
    proto/*.proto
