// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"
)

const createSite = `-- name: CreateSite :one
INSERT INTO
  sites (name)
VALUES
  ($1) RETURNING id, name
`

func (q *Queries) CreateSite(ctx context.Context, name string) (Site, error) {
	row := q.db.QueryRow(ctx, createSite, name)
	var i Site
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSites = `-- name: GetSites :many
SELECT
  id, name
FROM
  sites
`

func (q *Queries) GetSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, getSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
