BEGIN;

CREATE TABLE outbox (
  id bigint generated by default as identity PRIMARY KEY,
  partition_key text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  trace_context jsonb
);

CREATE INDEX idx_outbox_unpublished ON outbox (id)
WHERE
  published_at IS NULL;

COMMIT;